GET http://localhost:3000/test

###

GET http://localhost:3000/memberships

###

POST http://localhost:3000/memberships
Content-Type: application/json

{
    "name": "Bronze",
    "price": "2.99",
    "description": "30 days basic membership"
} 

###

DELETE http://localhost:3000/memberships/620e1af4e373f3444a8a98f7

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jack",
    "surname": "Russel",
    "email": "jack@gmail.com",
    "service_id": ""
} 

###

GET http://localhost:3000/users/-1