GET http://localhost:3000/test

###

GET http://localhost:3000/memberships

###

POST http://localhost:3000/memberships
Content-Type: application/json

{
    "name": "Silver",
    "price": "2.20",
    "description": "7 days membership"
} 

###

DELETE http://localhost:3000/memberships/620a6dd7fa26e00accc0b3e5